master:
  hosts:
    localhost:
      ansible_connection: local

workers:
  hosts:
    worker1:
      ansible_ssh_private_key_file: "/home/ubuntu/.ssh/mbocak_key.pem"
      ansible_user: ubuntu
      ansible_ssh_host: 54.73.84.175