master:
  hosts:
    localhost:
      ansible_connection: local

workers:
  hosts:
    worker1:
      ansible_ssh_private_key_file: /home/cloud_user/.ssh/id_rsa
      ansible_user: cloud_user
      ansible_ssh_host: 13.40.56.174
    worker2:
      ansible_ssh_private_key_file: /home/cloud_user/.ssh/id_rsa
      ansible_user: cloud_user
      ansible_ssh_host: 35.178.136.80