---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      package:
        upgrade: yes
        update_cache: yes

    - name: Install containerd
      package:
        name: containerd
        state: present
      notify: containerd restart
            
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
      
    - name: Create containerd config file
      copy:
        dest: /etc/containerd/config.toml
        content: |
          [plugins."io.containerd.grpc.v1.cri"]
            sandbox_image = "registry.k8s.io/pause:3.2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
      notify: containerd restart

  handlers:
    - name: run and enable containerd
      service:
        name: containerd
        state: started
        enabled: yes
      listen: containerd restart
