---
- hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update packages
      package:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Get Kubernetes apt repository GPG key
      shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
      args:
        creates: "{{ k8s_gpgpath }}"
      
    - name: Add Kubernetes apt repository
      apt_repository:
        filename: kubernetes
        repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubeadm, kubelet and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubeadm, kubelet and kubectl at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        force: yes

  post_tasks:
    - name: Initialize Kubernetes cluster with kubeadm and cidr network for Calico CNI (only on master)
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 
      when: "'master' in group_names"
      register: kubeadm_init

    - name: Create kubeconfig directory
      shell: mkdir -p $HOME/.kube
      when: "'master' in group_names"
      become: false

    - name: Copy admin.conf to local kubeconfig
      shell: sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
      when: "'master' in group_names"
      become: false

    - name: Change ownership of kubeconfig file
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
      when: "'master' in group_names"
      become: false

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command
      when: "'master' in group_names"

    - name: Join worker nodes to the cluster
      pause:
        prompt: |
          Run this command on nodes to join the cluster:

          {{ join_command.stdout }}

          Press enter to continue...

    - name: Install Calico network plugin (only on master)
      pause:
        prompt: |
          Run this command to enable networking in cluster via Calico CNI:
          
          kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
          
          Press enter to continue...
