---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      package:
        upgrade: yes
        update_cache: yes

    - name: Install containerd
      package:
        name: containerd.io
        state: present

    - name: Ensure containerd service is enabled and started
      service:
        name: containerd
        enabled: yes
        state: started

    - name: Configure containerd
      blockinfile:
        path: /etc/containerd/config.toml
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
        block: |
          [plugins."io.containerd.grpc.v1.cri"]
            sandbox_image = "registry.k8s.io/pause:3.2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
      loop:
        - name: Override sandbox (pause) image
