---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      package:
        upgrade: yes
        update_cache: yes

    - name: Install containerd
      package:
        name: containerd
        state: present
      notify: containerd restart
            
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
      

    - name: Create containerd config file
      copy:
        content: |
          version = 2

          root = "/var/lib/containerd"
          state = "/run/containerd"

          [grpc]
            address = "/run/containerd/containerd.sock"
            uid = 0
            gid = 0

          [debug]
            address = "/run/containerd/debug.sock"
            uid = 0
            gid = 0
            level = "info"

          [metrics]
            address = ""
            grpc_histogram = false

          [cgroup]
            path = ""

          [plugins."io.containerd.grpc.v1.cri"]
            default_runtime_name = "runc"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.other]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.other.options]
              SystemdCgroup = true
        dest: /etc/containerd/config.toml
      notify: containerd config changed

  handlers:
    - name: run and enable containerd
      service:
        name: containerd
        state: started
        enabled: yes
      listen: containerd installed

    - name: reload containerd service
      service:
        name: containerd
        state: reloaded
      listen: containerd config changed
