---
- hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update packages
      package:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Get Kubernetes apt repository GPG key
      shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
      args:
        creates: "{{ k8s_gpgpath }}"
      
    - name: Add Kubernetes apt repository
      apt_repository:
        filename: kubernetes
        repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubeadm, kubelet and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubeadm, kubelet and kubectl at current version
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        force: yes
      register: result

  post_tasks:
    - name: Initialize Kubernetes cluster with kubeadm and cidr network for Calico CNI (only on master)
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 
      when: "'master' in group_names"
      register: kubeadm_init

    - name: Create kubeconfig directory
      shell: mkdir -p $HOME/.kube
      when: "'master' in group_names"
      become: false

    - name: Copy admin.conf to local kubeconfig
      shell: sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
      when: "'master' in group_names"
      become: false

    - name: Change ownership of kubeconfig file
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
      when: "'master' in group_names"
      become: false

    - name: Join worker nodes to the cluster
      shell: "{{ item }}"
      with_items:
        - kubeadm join --token {{ kubeadm_init.results[0].stdout_lines[-1] }} {{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}:6443 --discovery-token-ca-cert-hash sha256:{{ kubeadm_init.results[1].stdout_lines[-1] }}
      when: "'workers' in group_names"

    - name: Install Calico network plugin (only on master)
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml --validate=false
      when: "'master' in group_names"

